name: dreamer
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  - hcc
dependencies:
  - python=3.8
  - setuptools=59.5.0
  - wheel<0.40.0
  - pytorch-gpu=2.0.0
  - torchvision
  - cudatoolkit=11.4
  - pillow
  - numpy=1.23.5
  - pandas
  - omegaconf
  - termcolor
  - gym==0.21.0
  - wandb
  - imageio
  - moviepy
  - pip
  - tensorboard
  - ruamel.yaml==0.17.4
  - free-mujoco-py
  - mujoco-py<3.0.0
  - dm_control=1.0.9
