name: dreamer
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - setuptools=65.5.0
  - wheel<0.40.0
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - tensorboard
  - gym==0.19.0
  - dm_control==1.0.9
  - ruamel.yaml==0.17.4
  - mujoco=2.3
  - moviepy==1.0.3

